import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { getAllPosts } from "../lib/api";
import Post from "../interfaces/post";
import Container from "../components/container";
import PostCard from "../components/postCard";

type allPostsProps = {
  allPosts: Post[];
};

const Home = ({ allPosts }: allPostsProps) => {
  return (
    <div className={styles.container}>
      <Head>
        <title> Next Blog </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to Next.js blog</h1>
        <Container>
          {allPosts.map((post, idx) => (
            <PostCard
              styles={styles.card}
              key={idx}
              slug={post.slug}
              title={post.title}
              excerpt={post.excerpt}
            ></PostCard>
          ))}
        </Container>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;

export const getStaticProps = async () => {
  const allPosts = getAllPosts(["title", "slug", "excerpt"]);

  return {
    props: { allPosts },
  };
};
